# Generated by Django 2.2.3 on 2019-07-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_useraccounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='account',
            new_name='email_account',
        ),
    ]
