# Generated by Django 2.2.3 on 2019-07-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaapp', '0004_auto_20190727_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.CharField(blank=True, max_length=100, null=True, verbose_name='user_account')),
                ('total_followers', models.CharField(blank=True, max_length=100, null=True, verbose_name='user_package')),
                ('total_follows', models.CharField(blank=True, max_length=100, null=True)),
                ('pending_follow_request', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
