# Generated by Django 2.2.3 on 2019-07-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0006_auto_20190727_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='email_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='user_account'),
        ),
    ]
